### ISSUE TITLE
Doesn't work with gulp-sass

### ISSUE THREAD

**Issue by danreeves** [britco/node-sass-globbing#2]
The variable passed to the function are incorrect, e.g.:

``` js
// url: modules/* 
// prev: stdin 
// done: function done(data) {
//        bridge.success(data);
//       }
```

This is because when using `opts.data` to pass the content of a sass file in, rather than `opts.file` to pass the file name, sass doesn't know the cwd.

We could conditionally use `this.includePaths` inside the importer ([which works in node-sass > 3.0.0](https://github.com/sass/node-sass#importer--v200---experimental)) but would require potentially looping through an array of paths and applying the glob to each. Maybe the original [sass-globbing](https://github.com/chriseppstein/sass-globbing) can help.

I also created an issue on gulp-sass (https://github.com/dlmanning/gulp-sass/issues/324) about an alternative work around.

**Comment by pdufour** [comment]
Hi @danreeves thanks for submitting this issue. It seems like using `includePaths` would be the way to go, since that is the way the resolver works internally. https://github.com/sass/node-sass#data. Unfortunately I am not actively working on this project since there are some outstanding issues when you use a custom importer and have a lot of files. https://github.com/sass/node-sass/issues/857.

I'm happy to look at a PR though if you want to submit one.

**Comment by danreeves** [comment]
Hi,

I spent some more time thinking about this issue and realised it would be difficult to resolve relative imports using the `includePaths`. I've worked around this issue by forking gulp-sass to use `opts.file`.

I think, for now, this issue can closed and gulp-sass should get a fix. At least until node-sass imports stabilize and it's clear how they should work with `opts.data` (if at all).

Thanks!
